kind: Namespace
apiVersion: v1
metadata:
  name: tona-ns
  labels:
    name: tona-ns    
---
apiVersion: v1
kind: Namespace
metadata:
  name: tona-monitoring-ns
  labels:
    name: tona-monitoring-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    name: istio-system
