kind: Service
apiVersion: v1
metadata:
  name: movierating-frontend
  namespace: tona-ns
spec:
  selector:
    app: movierating-frontend
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 80
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: movierating-frontend
  namespace: tona-ns
spec:
  selector:
      matchLabels:
        app: movierating-frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: movierating-frontend
      annotations:
          prometheus.io/scrape: 'true'
          prometheus.io/port: '9090'
    spec:
      containers:
        - name: movierating-frontend
          image: movieratingappcontainerregistry.azurecr.io/movierating-frontend:latest
          ports:
            - containerPort: 80
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: movierating-ingress
  namespace: tona-ns
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: movierating-frontend
          servicePort: 9090